###
# build dockerfile multistage. to build base, sde and prod image exec:
# $> docker compose build
# to install a specific repo or branch on prod image :
# $> REPO_SRC="https://repo.git" REPO_BRANCH="dev_branch" docker compose build
###

services:

  base:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    image: dams_base:1.6.0

  prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
      args:
        - REPO_BRANCH=${REPO_BRANCH:-main}
        # - REPO_SRC= use it to change repo
    depends_on:
      - base
    image: dams_prod:${REPO_BRANCH:-latest}


